### PR TITLE
Improve db insertion performance

### PR DESCRIPTION
**Pull request by alpha0010**
Wrapping in a transaction gives an order of magnitude improvement to performance.

### CODE REVIEW

**Comment by tom--** [comment]
Hi @alpha0010, thanks for the PR.

I don't see an order of magnitude difference in execution time—only about 20%.

- Inserting U+00 .. U+24F takes 0.50 s without transaction and 0.40 s with.
- Inserting U+00 .. U+FFFF takes 13.4 s without transaction and 10.9 s with.

Perhaps the difference depends on latency between db client and server, which was very small in my tests.

In any case, I think it's a good idea to use a transaction regardless of performance. However, I'd prefer to see a try/catch structure around the code between tx begin and commit with a rollback in the catch branch.

**Comment by alpha0010** [comment]
Guess I have a slow machine...

```bash
# Before
$ time ./c2ct newtable
PHP IntlChar Unicode version 12.0.0.0
Range 00000 to 01FFF, 8192 codepoints
Inserted 6962, excluded 1230
Done
Total 8192 codepoints, inserted 6962, excluded 1230

real	0m29.457s
user	0m0.472s
sys	0m0.816s

# After
$ time ./c2ct newtable
PHP IntlChar Unicode version 12.0.0.0
Range 00000 to 01FFF, 8192 codepoints
Inserted 6962, excluded 1230
Done
Total 8192 codepoints, inserted 6962, excluded 1230

real	0m4.714s
user	0m0.308s
sys	0m0.848s
```

**Comment by tom--** [comment]
That is indeed slow. Your mysqld runs on a Raspberry Pi? :P

**Comment by tom--** [comment]
Thanks for the PR

**Pull request merged**
